### ISSUE TITLE
Question: Makam vs. Teyjus

### ISSUE THREAD

**Issue by d4hines** [astampoulis/makam#102]
Hi!
I'd like to learn λ-Prolog. I've picked up a copy of Dale Miller's _Programming with Higher Order Logic_. It recommends the Teyjus system. Do you think I could get by using Makam instead? Are there large differences in syntax or semantics I should be concerned about?
Thanks!
Daniel Hines

**Comment by astampoulis** [comment]
Hi Daniel!

Thanks for taking an interest in Makam!

Makam does depart from λProlog in a few cases, so you'd have to adapt the examples that you find in the book. The semantics I would say are largely the same, outside of the lack of the λProlog module system in Makam. The main departures are in the syntax and the standard libraries. For syntax, I could prepare a "conversion key" table if it would be helpful, as most of the changes are quite simple. The standard libraries might prove more tricky though; I haven't worked through the book so I'm not sure what issues you'll run into for those.

An option that might be easier to work with than Teyjus and that conforms to the λProlog standard much more closely than Makam is ELPI: https://github.com/LPCIC/elpi/
Using ELPI might be the easiest way to learn the base λProlog language working through the book. Once you are comfortable with the language, learning to do the same things in Makam should be simple, should you decide to use Makam instead.

In any case I'd be curious to know of your experience with the book and working through it in ELPI or Makam, so please keep me posted! And if you go the Makam route, happy to help with any potential issues you run into.

**Comment by d4hines** [comment]
I've decided the λ-Prolog book is too advanced/far removed from my present goal, which is to implement an extension of calculus of constructions. I'm playing around with Makam and really liking it. I think I'll return to the book when I have more grounding both in formal logic and in playing with Makam.

**Comment by astampoulis** [comment]
Sounds good @d4hines !
