### ISSUE TITLE
Loading a file from REPL

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#112]
For REPL driven development, it would be great to be able to import definitions from a file in REPL with a single command.

**Comment by astampoulis** [comment]
Hi @suhr , thanks for opening the issue. Could you elaborate on the use case -- do `%use` or `%usenew` work for you? `%use` imports a file if not imported already, and `%usenew` resets the state and loads the file anew -- in which case you might have to add back any definitions you've done in the REPL.

Both run the queries contained in the file, unless they're specified as test cases instead.

**Comment by suhr** [comment]
That indeed works, thanks. Now I can add a REPL support to the VS Code extension.

Such things are hard to discover, so having a cheat sheet would be great.
