### ISSUE TITLE
Feature request: use `structural` on the default implementation of `eqv`

### ISSUE THREAD

**Issue by teofr** [astampoulis/makam#64]
`eqv` seems to be useful when defining particular equivalence relations. For instance, unordered equivalence between `set`s. However, the problem in my opinion is that the default implementation (which is just syntactic equivalence) should do a recursive call to `eqv`.

The problem arises when using types that have subterms from other types, that could have an explicit `eqv` relation. For instance:

```
# eqv (expansion L) (expansion R) ?    
Impossible.

# eqv [ expansion L] [expansion R] ?
Yes:
L := R,
R := R.

# eqv (dyn (expansion L) ) (dyn (expansion R ) )?
Yes:
R := R,
L := R.
```
`expansion` has an explicit `eqv` relation, but `list expansion` doesn't care about that.

A different approach would be to redefine `eqv` for every datatype (`list`, `map`, ...) (like manually defining `Eq` on Haskell), but I think `structural` should work.

I'd be happy to make this change in a PR, let me know if you think this makes sense or if there's any particular reason not to do it.

**Comment by astampoulis** [comment]
This makes a lot of sense! I don't see any reason not to do it, I think it's worth trying out. Maybe it could also simplify a couple of cases, and I would guess that we could remove the `without_eqv_refl` hack too.

There could be an impact on the performance of the examples, since `structural` is quite slow; at the same time, I do not recall how much `eqv` is used, so it might be a non-issue.

**Comment by teofr** [comment]
I think `without_eqv_refl` is still needed, maybe I'm missing something though.

Ok, I'll give it a try and hope anything breaks.

**Comment by teofr** [comment]
_There are no simple issues..._

Adding this feature in the easy way creates a circular dependency (`eqv` -> `generic` -> `list` -> `eqv`).

I'm not really sure if this is fixable or not, or if there's a natural way of fixing it in Makam (maybe separating declarations from implementations, but seems a lot of work).

**Comment by astampoulis** [comment]
I see; I'll take a look at that and report back. Implementations and declarations are already separate in Makam -- you don't have to declare any rules when you declare a predicate, and you can always add rules later. But the circularity could still be there.

**Comment by astampoulis** [comment]
I see what you mean now. I think in this case we should just remove the use of `eqv` in `list.contains`, and repurpose the predicate for full equality; I don't think the predicate is used anywhere so far, so there shouldn't be an impact. (Also, most other `list` predicates do not make use of `eqv`, so this behavior is a little odd to start with.) That will allow us to move `eqv` after `generic`.

**Comment by astampoulis** [comment]
Closing at this time based on the findings of #73
