### ISSUE TITLE
Infinite loop problem in the definition of `guardmany_aux`

### ISSUE THREAD

**Issue by teofr** [astampoulis/makam#65]
`guardmany_aux` defined in:
https://github.com/astampoulis/makam/blob/36877d4b0915e994972f08a2e38f4986f6ea2579/stdlib/guard.makam#L3-L9
... in particular, lines 8-9 loop forever when backtracking, for instance:
```
(guardmany_aux [X] Trigger (print "t") , failure)?
```

I'll write a PR as soon as I have some time, it doesn't look complicated, but wanted to put it up here.

**Comment by astampoulis** [comment]
Thanks for reporting this! Let me know if #67 works.

**Comment by teofr** [comment]
Thanks!
