### ISSUE TITLE
`pa_monad_custom` is no longer supported

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#78]
The last commit in pa_monad_custom was 7 years ago: https://bitbucket.org/camlspotter/pa_monad_custom/commits/

It is impossible to compile on a modern system: omake errors with `can not find OMakeroot or Root.om` while oasis errors with `OASIS format version '0.2' is not supported`.

**Comment by astampoulis** [comment]
Thanks for reporting this issue @suhr! 

I should be able to update the code-base to use `let`-syntax instead and drop the dependency. Might take some time (there's a couple of other issues that have come up, and don't have a ton of free cycles at the moment), but I'll keep this open until I'm able to address.

**Comment by astampoulis** [comment]
Fixed this as part of #106.
