### ISSUE TITLE
Single line comments

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#79]
They are very convenient to have.

**Comment by astampoulis** [comment]
Thanks for the suggestion @suhr. I've been following the OCaml convention for comments which only includes block syntax `(* ... *)`. I'll look into adding single line comments maybe in the way that lambdaProlog does it (`% ...`).

**Comment by astampoulis** [comment]
Added in #82. @suhr If you update to the latest version on `npm`, `0.7.30`, you should be able to use the new syntax.
