### ISSUE TITLE
File list.makam not found

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#81]
```
!! Error in file ./doc/razbor.makam, line 1, characters 1-11:
   File list.makam not found (searched: [./doc/list.makam; /home/suhr/.npm-packages/lib/node_modules/makam/list.makam; /home/suhr/.npm-packages/lib/node_modules/makam/stdlib-cache/list.makam]).
```

While trying to import with `%use list`.

There's `list.makam` in `/home/suhr/.npm-packages/lib/node_modules/makam/stdlib/`. But there's no `list.makam` in `/home/suhr/.npm-packages/lib/node_modules/makam/stdlib-cache/`:

```
% ls -1 /home/suhr/.npm-packages/lib/node_modules/makam/stdlib-cache
1023965001.makam-cache
1098923814.makam-cache
1152327979.makam-cache
1406994528.makam-cache
1526945188.makam-cache
1584950368.makam-cache
1805749169.makam-cache
1845788431.makam-cache
1947437720.makam-cache
1954381117.makam-cache
910116983.makam-cache
990541764.makam-cache
```

Makam version: from npm.

**Comment by astampoulis** [comment]
The `stdlib` directory is not included in the search path by default, so you have to do `%use "stdlib/list".` instead.

However, in most cases you shouldn't need to import `list` directly. The `stdlib/init.makam` file should be loaded by default, which includes loading `list`. Are you noticing different behavior? Happy to take a look at your code if you are having other unexpected issues.

`stdlib-cache` is used for a different purpose, so it is expected that there is no `list.makam` in it. It is used for caching the results of parser generation in the standard library, as that is quite expensive to do every time.

Let me know if this helps resolve the issue!

**Comment by suhr** [comment]
I see, thanks. But the way, is there any support for namespacing to avoid name clash?

**Comment by astampoulis** [comment]
Yes, there is. The syntax is:

```
%extend foo.
(...definitions...)
%end.
```

You can then refer to definitions in foo as `foo.bar`. You could also use a `use` statement within the `extend`, to namespace all the definitions. There's some examples of that in `stdlib/syntax` if you'd like to take a look.
