### ISSUE TITLE
Better error formatting

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#85]
Right now, makam errors look like this:

```
!! Error in file ./razbor.makam, line 174, characters 1-12:
   Term of type ty -> ty -> ty -> prop,
   whereas expected a type of form ty -> ty -> ty -> ty -> prop.
```

But it would be better if they looked like this:

```
error[E0308]: mismatched types
  --> src/format.rs:52:1
   |
51 |   ) -> Option<String> {
   |        -------------- expected `Option<String>` because of return type
52 | /     for ann in annotations {
53 | |         match (ann.range.0, ann.range.1) {
54 | |             (None, None) => continue,
55 | |             (Some(start), Some(end)) if start > end_index => continue,
...  |
71 | |         }
72 | |     }
   | |_____^ expected enum `std::option::Option`, found ()
```

(this is [annotate-snippets](https://github.com/rust-lang/annotate-snippets-rs) generated error)

Regardless of error formatting, it's important to have `<file name>:line:column` references, because they can be followed by a text editor.

**Comment by brendanzab** [comment]
Yeah, I'd echo that `<file name>:line:column` in the output would be extremely useful! Nicely rendered snippets with underlines would also be super helpful, but as the maintainer of [codespan](https://github.com/brendanzab/codespan) (another diagnostic reporting library) I know it can be a bit of a pain to implement!

**Comment by astampoulis** [comment]
Thanks @suhr @brendanzab, will look to make this change (plus the corresponding changes to the web service etc.). For denoting spans, is the standard format `<file name>:line:column-<file name>:line:column`?

**Comment by brendanzab** [comment]
Here's a link to [one standard for diagnostic locations](https://www.gnu.org/prep/standards/html_node/Errors.html). AFAIK tool support for ranges is less common though (which is is a bit frustrating), which is why rustc just displays the starting line and column.

**Comment by astampoulis** [comment]
Thanks for the reference @brendanzab. Ranges are important for highlighting part of the code in the Web UI use case (e.g. in [the tutorial](https://astampoulis.github.io/blog/makam-tutorial-01/)). So I'm wondering what editors you and @suhr are using, and if the format `sourcefile:line1.column1-line2.column2` would work?

**Comment by suhr** [comment]
I'm using VS Code, and it doesn't seem to support `sourcefile:line1.column1-line2.column2` format.

**Comment by astampoulis** [comment]
@suhr Just did some testing of this on VS Code, it seems like the `sourcefile:line1` part is still recognized to point to the line containing the error. (Granted, it's not as nice as getting the full span, but seems to be an improvement over the present state.) Also for cases where the span is in a single line, the format `sourcefile:line1:column1-column2` gets you to the actual start of the span.

**Comment by brendanzab** [comment]
> Ranges are important for highlighting part of the code in the Web UI use case (e.g. in [the tutorial](https://astampoulis.github.io/blog/makam-tutorial-01/)). So I'm wondering what editors you and @suhr are using, and if the format `sourcefile:line1.column1-line2.column2` would work?

Yeah I'm using VS code too.

Is the Web UI parsing the human-facing diagnostics to print the errors? Wondering if something like a structured diagnostic output would be helpful in this case. For example rustc has `--error-format human|json|short` for allowing other tools (like screen readers) to consume the errors.

TBH I didn't actually realise you could run the tutorial in the browser! The 'run' button in the corner is pretty easy to miss! Definitely really cool though :)

**Comment by astampoulis** [comment]
Let me know if after #96 this works better in VSCode!

@brendanzab The Web UI is indeed parsing the human-facing diagnostics, but yeah, eventually a more structured format could be helpful. I would like to keep ranges in though even outside the Web UI, as it's sometimes helpful in type errors. But if the present solution doesn't work we'll try something else :smile:

And a few people have missed the 'run' button, I should make that more discoverable :smile: I've used the Web UI for live editing in presentations too, e.g. for the [ICFP presentation](https://rawcdn.githack.com/astampoulis/makam-paper-funpearl/5634404aad01b3c62514cfeeebfe44a4122f5c13/slides/index.html)

**Comment by brendanzab** [comment]
Yeah, thanks anyway, greatly appreciate it!
