### ISSUE TITLE
%\n is a syntax error

### ISSUE THREAD

**Issue by brendanzab** [astampoulis/makam#89]
Just ran across this:

```prolog
%
```

Produces the following error:

```
$ makam error --run-tests

	Makam, version 0.7.30


!! Error in file ./error.makam, line 1, character 1:
   Parse error.
```

This can be annoying if you want to make stacked line comments, like:

```prolog
% A dependently typed binary data description language, prototyped in Makam!
%
% This is an extension of Martin Löf type theory, with some builtin data types,
% like booleans, integers, and arrays, and support for defining binary format
% descriptions.
```

I'm guessing this is a result of [this rule](https://github.com/astampoulis/makam/blob/04b676495d6f72f24fcc0d7171f15e2a41c91d2b/grammars/makamGrammar.peg#L598) in the parser, added in #82?

**Comment by astampoulis** [comment]
:+1: Thanks for reporting this issue @brendanzab. That is indeed the source of the error; #91 should fix this.
